# pqc_des_compat.py — generated by PQC Scanner
# Drop-in replacement for DES/3DES cipher objects using AES-256-GCM.
#
# Usage: cipher = AESGCMCipher(key)  # replaces DES.new(key, mode, ...)
#        ciphertext = cipher.encrypt(plaintext)   # unchanged
#        plaintext  = cipher.decrypt(ciphertext)  # unchanged
#
# Ciphertext format: <nonce (12 bytes)> | <AES-GCM ciphertext>
# Key is hashed with SHA-256 to derive a 256-bit AES key
# (handles short DES keys of 8 or 16 bytes transparently).
import hashlib
import os
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

_NONCE_SIZE = 12


class AESGCMCipher:
    """Drop-in replacement for DES.new() / DES3.new() using AES-256-GCM.

    Differences from DES:
    - Key is always derived to 256 bits via SHA-256 (DES 8-byte key is too short for AES-256)
    - Ciphertext is NOT compatible with DES-encrypted data — re-encrypt existing data
    - Nonce is generated randomly per encrypt call and prepended to ciphertext
    - Authenticated encryption: decryption raises cryptography.exceptions.InvalidTag on tampering
    """

    def __init__(self, key: bytes) -> None:
        # Derive a 256-bit key regardless of input key length
        self._key = hashlib.sha256(key).digest()

    def encrypt(self, plaintext: bytes) -> bytes:
        """Encrypt plaintext and return nonce + ciphertext."""
        nonce = os.urandom(_NONCE_SIZE)
        ct = AESGCM(self._key).encrypt(nonce, plaintext, None)
        return nonce + ct

    def decrypt(self, ciphertext: bytes) -> bytes:
        """Decrypt ciphertext produced by this class."""
        nonce = ciphertext[:_NONCE_SIZE]
        ct = ciphertext[_NONCE_SIZE:]
        return AESGCM(self._key).decrypt(nonce, ct, None)
