# pqc_crypto_helpers.py — generated by PQC Scanner
# ML-KEM-768 + AES-256-GCM hybrid encryption helpers.
# Replaces RSA OAEP encrypt/decrypt with a post-quantum equivalent.
#
# Ciphertext wire format: <kem_ct (1088 bytes)> | <nonce (12 bytes)> | <aes_gcm_ct>
# Requires: pqcrypto, cryptography
import hashlib
import os
from pqcrypto.kem import ml_kem_768 as mlkem768
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

_KEM_CT_SIZE = 1088  # ml_kem_768 ciphertext is always 1088 bytes
_NONCE_SIZE = 12


def mlkem768_hybrid_encrypt(public_key, plaintext: bytes) -> bytes:
    """Encrypt plaintext using ML-KEM-768 key encapsulation + AES-256-GCM.

    Args:
        public_key: ML-KEM-768 public key (bytes or pqcrypto key object)
        plaintext: Data to encrypt
    Returns:
        Ciphertext bytes (KEM ciphertext + nonce + AES-GCM ciphertext)
    """
    kem_ct, shared_secret = mlkem768.enc(public_key)
    aes_key = hashlib.sha256(shared_secret).digest()
    nonce = os.urandom(_NONCE_SIZE)
    aesgcm = AESGCM(aes_key)
    aes_ct = aesgcm.encrypt(nonce, plaintext, None)
    return kem_ct + nonce + aes_ct


def mlkem768_hybrid_decrypt(private_key, ciphertext: bytes) -> bytes:
    """Decrypt ciphertext using ML-KEM-768 key decapsulation + AES-256-GCM.

    Args:
        private_key: ML-KEM-768 private key (bytes or pqcrypto key object)
        ciphertext: Bytes produced by mlkem768_hybrid_encrypt
    Returns:
        Decrypted plaintext bytes
    """
    kem_ct = ciphertext[:_KEM_CT_SIZE]
    nonce = ciphertext[_KEM_CT_SIZE:_KEM_CT_SIZE + _NONCE_SIZE]
    aes_ct = ciphertext[_KEM_CT_SIZE + _NONCE_SIZE:]
    shared_secret = mlkem768.dec(private_key, kem_ct)
    aes_key = hashlib.sha256(shared_secret).digest()
    aesgcm = AESGCM(aes_key)
    return aesgcm.decrypt(nonce, aes_ct, None)
